name: Build test

on:
  pull_request:
    branches:
      - live

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout live
        uses: actions/checkout@v2
      - name: Setup node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: LUCAS_WIKI_GA=${{ secrets.LUCAS_WIKI_GA }} npm run build
