name: Build and Deploy

on:
  push:
    branches:
      - live

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout live
        uses: actions/checkout@v2
      - name: Setup node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: LUCAS_WIKI_GA=${{ secrets.LUCAS_WIKI_GA }} npm run build
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./docs/.vuepress/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./docs/.vuepress/dist
      - name: Deploy firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project lucas-wiki
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
