name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./docs/.vuepress/dist

